#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets these two at the top of the stages section.
TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does and how long it takes.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" <minutes> — clear the screen, then announce a stage and show
# progress + time remaining. Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set the two totals to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=14
TOTAL_MINUTES=50

SETUP_STATE_FILE="${SETUP_STATE_FILE:-.setup.vars}"
DEV_VARS_FILE="${DEV_VARS_FILE:-.dev.vars}"
WIZARD_DRY_RUN="${WIZARD_DRY_RUN:-0}"
ENV_FILE="$SETUP_STATE_FILE"

die() {
  printf '  %s✗ %s%s\n' "$RED" "$1" "$RESET" >&2
  exit 1
}

open_setup_url() {
  if [[ "$WIZARD_DRY_RUN" == "1" ]]; then
    note "dry run: would open $1"
    return
  fi
  open_url "$1"
}

saved_value() {
  local file="$1" key="$2" line
  [[ -f "$file" ]] || return 1
  line=$(grep -E "^${key}=" "$file" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

write_to_file() {
  local file="$1" key="$2" value="$3" previous="$ENV_FILE"
  ENV_FILE="$file"
  write_env "$key" "$value"
  ENV_FILE="$previous"
}

capture_value() {
  local file="$1" key="$2" prompt="$3" previous="$ENV_FILE" value
  ENV_FILE="$file"
  ask "$key" "$prompt"
  value="${!key}"
  [[ -n "$value" ]] || die "$key cannot be empty."
  write_env "$key" "$value"
  ENV_FILE="$previous"
}

capture_secret() {
  local file="$1" key="$2" prompt="$3" previous="$ENV_FILE" value
  ENV_FILE="$file"
  ask_secret "$key" "$prompt"
  value="${!key}"
  [[ -n "$value" ]] || die "$key cannot be empty."
  write_env "$key" "$value"
  ENV_FILE="$previous"
}

validate_slug() {
  local slug="$1"
  [[ ${#slug} -le 39 ]] || return 1
  [[ "$slug" =~ ^[a-z][a-z0-9]{1,18}-[a-z][a-z0-9]{1,18}$ ]]
}

generate_codenames() {
  local adjectives=(calm clear copper gentle lucid quiet silver steady subtle vivid)
  local nouns=(badger cedar comet finch harbor lantern meadow otter pebble willow)
  local candidate existing
  CODENAME_OPTIONS=()

  while (( ${#CODENAME_OPTIONS[@]} < 3 )); do
    candidate="${adjectives[$((RANDOM % ${#adjectives[@]}))]}-${nouns[$((RANDOM % ${#nouns[@]}))]}"
    existing=" ${CODENAME_OPTIONS[*]-} "
    [[ "$existing" == *" $candidate "* ]] || CODENAME_OPTIONS+=("$candidate")
  done
}

select_codename() {
  local current selection custom
  current=$(saved_value "$SETUP_STATE_FILE" INFRA_SLUG || true)
  if [[ -n "$current" ]] && validate_slug "$current"; then
    say "Existing infrastructure codename: $current"
    if confirm "Keep this codename and its existing resources?"; then
      INFRA_SLUG="$current"
      return
    fi
  fi

  generate_codenames
  say "Choose one neutral infrastructure codename:"
  step "1 — ${CODENAME_OPTIONS[0]}"
  step "2 — ${CODENAME_OPTIONS[1]}"
  step "3 — ${CODENAME_OPTIONS[2]}"
  step "4 — enter a custom adjective-noun slug"
  printf '  %sSelection [1-4]:%s ' "$BOLD" "$RESET"
  read -r selection || true

  case "$selection" in
    1|2|3) INFRA_SLUG="${CODENAME_OPTIONS[$((selection - 1))]}" ;;
    4)
      while true; do
        printf '  %sCustom slug:%s ' "$BOLD" "$RESET"
        read -r custom || true
        if validate_slug "$custom"; then
          INFRA_SLUG="$custom"
          break
        fi
        warn "use two lowercase words separated by one hyphen; each word may contain letters or digits"
      done
      ;;
    *) die "Choose 1, 2, 3, or 4." ;;
  esac

  write_to_file "$SETUP_STATE_FILE" INFRA_SLUG "$INFRA_SLUG"
}

ensure_node() {
  if command -v node >/dev/null 2>&1; then
    local major
    major=$(node -p 'Number(process.versions.node.split(".")[0])')
    (( major >= 22 )) || die "Node 22+ is required; Node 24 is recommended. Visit https://nodejs.org/en/download."
    say "Node $(node --version) is ready."
    return
  fi

  say "Node 24 is required. macOS command: brew install node@24"
  say "All platforms: https://nodejs.org/en/download"
  if command -v brew >/dev/null 2>&1 && confirm "Install Node 24 with Homebrew now?"; then
    brew install node@24
  else
    open_setup_url "https://nodejs.org/en/download"
    pause "Install Node 24, then press Enter to re-check."
  fi
  command -v node >/dev/null 2>&1 || die "Node is still unavailable."
}

ensure_pnpm() {
  local major=0
  if command -v pnpm >/dev/null 2>&1; then
    major=$(pnpm --version 2>/dev/null | cut -d. -f1 || echo 0)
  fi
  if (( major >= 11 )); then
    say "pnpm $(pnpm --version) is ready."
    return
  fi

  say "pnpm 11 is required. Exact command: corepack install --global pnpm@11.21.0"
  confirm "Install or update pnpm with Corepack now?" || die "pnpm setup was not approved."
  command -v corepack >/dev/null 2>&1 || die "Corepack is unavailable; install Node 24 first."
  corepack enable
  corepack install --global pnpm@11.21.0
  command -v pnpm >/dev/null 2>&1 || die "pnpm is still unavailable."
}

ensure_gh() {
  if command -v gh >/dev/null 2>&1; then
    say "GitHub CLI $(gh --version | head -n1) is ready."
  else
    say "GitHub CLI is required. macOS command: brew install gh"
    say "Linux instructions: https://github.com/cli/cli/blob/trunk/docs/install_linux.md"
    if command -v brew >/dev/null 2>&1 && confirm "Install GitHub CLI with Homebrew now?"; then
      brew install gh
    else
      open_setup_url "https://cli.github.com/"
      pause "Install GitHub CLI, then press Enter to re-check."
    fi
    command -v gh >/dev/null 2>&1 || die "GitHub CLI is still unavailable."
  fi

  if ! gh auth status >/dev/null 2>&1; then
    confirm "Authenticate GitHub CLI in the browser now?" || die "GitHub authentication is required."
    gh auth login --web --git-protocol https
  fi
}

ensure_project_dependencies() {
  if [[ -x node_modules/.bin/wrangler ]]; then
    say "Wrangler $(pnpm exec wrangler --version | head -n1) is ready from this repository."
    return
  fi

  say "Wrangler is declared in package.json and will be installed with the repository dependencies."
  confirm "Run pnpm install now?" || die "Dependency installation was not approved."
  pnpm install --frozen-lockfile
  [[ -x node_modules/.bin/wrangler ]] || die "The local Wrangler installation failed."
}

cf_wrangler() {
  CLOUDFLARE_API_TOKEN="$CF_DEPLOY_TOKEN" \
    CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_ID" \
    pnpm exec wrangler "$@"
}

load_saved_cloudflare_credentials() {
  CF_DEPLOY_TOKEN=$(saved_value "$SETUP_STATE_FILE" CLOUDFLARE_API_TOKEN || true)
  CF_ACCOUNT_ID=$(saved_value "$SETUP_STATE_FILE" CLOUDFLARE_ACCOUNT_ID || true)

  [[ -n "$CF_DEPLOY_TOKEN" && "$CF_ACCOUNT_ID" =~ ^[a-fA-F0-9]{32}$ ]]
}

capture_cloudflare_credentials() {
  say "Cloudflare Workflows requires the Workers Paid plan for this deployment."
  open_setup_url "https://dash.cloudflare.com/?to=/:account/workers/plans"
  step "Select the account you will use, activate Workers Paid, and confirm billing."
  pause "Press Enter after Workers Paid is active."
  open_setup_url "https://dash.cloudflare.com/profile/api-tokens"
  step "Create a custom token scoped to this account only."
  step "Grant Account Settings Read, Workers Scripts Edit, D1 Edit, and Workers R2 Storage Edit."
  step "Do not grant zone access or unrelated account permissions. Copy the token once."
  capture_secret "$SETUP_STATE_FILE" CLOUDFLARE_API_TOKEN "Paste the Cloudflare deployment token:"
  CF_DEPLOY_TOKEN=$(saved_value "$SETUP_STATE_FILE" CLOUDFLARE_API_TOKEN)
  step "In the account overview, copy the 32-character Account ID."
  capture_value "$SETUP_STATE_FILE" CLOUDFLARE_ACCOUNT_ID "Paste the Cloudflare Account ID:"
  CF_ACCOUNT_ID=$(saved_value "$SETUP_STATE_FILE" CLOUDFLARE_ACCOUNT_ID)
  [[ "$CF_ACCOUNT_ID" =~ ^[a-fA-F0-9]{32}$ ]] || die "Cloudflare Account ID must be 32 hexadecimal characters."
}

configure_wrangler() {
  local slug="$1" d1_id="$2"
  node scripts/update-wrangler-config.mjs wrangler.jsonc "$slug" "$d1_id"
}

json_id() {
  node -e 'let input="";process.stdin.on("data",d=>input+=d);process.stdin.on("end",()=>{const value=JSON.parse(input);process.stdout.write(value.uuid||value.id||"")})'
}

put_worker_secret() {
  local name="$1" value="$2"
  if [[ "$WIZARD_DRY_RUN" == "1" ]]; then
    note "dry run: would upload Worker secret $name"
    return
  fi
  printf '%s' "$value" | cf_wrangler secret put "$name" >/dev/null
  printf '  %s✓ uploaded%s Worker secret %s\n' "$GREEN" "$RESET" "$name"
}

if [[ "${1:-}" == "--check" ]]; then
  validate_slug "quiet-harbor" || die "Internal slug validation failed."
  [[ -f wrangler.jsonc && -f package.json && -f .dev.vars.example ]] || die "Required project files are missing."
  [[ -f seed/foundation.sql && -f seed/catalog.sql ]] || die "The seed files the wizard imports are missing."
  printf 'Wizard static self-check passed.\n'
  exit 0
fi

banner "RFQ Relay infrastructure setup"

stage "Prerequisites and authentication" 4
say "We will verify the local toolchain before any external resource is changed."
ensure_node
ensure_pnpm
ensure_gh
ensure_project_dependencies

stage "Choose a neutral codename" 2
say "This stable slug names the public repository and Cloudflare resources."
say "RFQ Relay remains the product name shown in the application."
select_codename

stage "Create or reuse the GitHub repository" 3
if git remote get-url origin >/dev/null 2>&1; then
  note "Keeping existing origin: $(git remote get-url origin)"
else
  open_setup_url "https://github.com/new"
  say "The wizard can create a public repository named $INFRA_SLUG under your authenticated account."
  if confirm "Create that GitHub repository and add it as origin?"; then
    if [[ "$WIZARD_DRY_RUN" == "1" ]]; then
      note "dry run: would create GitHub repository $INFRA_SLUG"
    else
      gh repo create "$INFRA_SLUG" --public --source=. --remote=origin
    fi
  else
    die "Repository creation was not approved. Re-run when ready."
  fi
fi

stage "Cloudflare authentication" 8
if load_saved_cloudflare_credentials; then
  note "Verifying saved Cloudflare credentials from $SETUP_STATE_FILE."
  if ! cf_wrangler whoami >/dev/null; then
    warn "The saved Cloudflare credentials are no longer valid."
    capture_cloudflare_credentials
    cf_wrangler whoami >/dev/null || die "Wrangler could not authenticate with that account and token."
  fi
else
  capture_cloudflare_credentials
  cf_wrangler whoami >/dev/null || die "Wrangler could not authenticate with that account and token."
fi
say "Cloudflare authentication is ready."

stage "Provision or reuse Cloudflare resources" 4
DB_NAME="${INFRA_SLUG}-db"
BUCKET_NAME="${INFRA_SLUG}-artifacts"
say "D1: $DB_NAME"
say "R2: $BUCKET_NAME"
say "Workflow: ${INFRA_SLUG}-workflow (created with the Worker deployment)"
confirm "Provision missing D1/R2 resources and update wrangler.jsonc?" || die "Resource provisioning was not approved."
if [[ "$WIZARD_DRY_RUN" == "1" ]]; then
  note "dry run: would provision or reuse D1 and R2 resources"
  D1_DATABASE_ID="00000000-0000-0000-0000-000000000000"
else
  D1_INFO=$(cf_wrangler d1 info "$DB_NAME" --json 2>/dev/null || true)
  if [[ -z "$D1_INFO" ]]; then
    cf_wrangler d1 create "$DB_NAME" --location weur --update-config --binding DB
    D1_INFO=$(cf_wrangler d1 info "$DB_NAME" --json)
  else
    note "Keeping existing D1 database $DB_NAME."
  fi
  D1_DATABASE_ID=$(printf '%s' "$D1_INFO" | json_id)
  [[ -n "$D1_DATABASE_ID" ]] || die "Could not resolve the D1 database ID."

  if cf_wrangler r2 bucket info "$BUCKET_NAME" >/dev/null 2>&1; then
    note "Keeping existing R2 bucket $BUCKET_NAME."
  else
    cf_wrangler r2 bucket create "$BUCKET_NAME" --location weur --update-config --binding ARTIFACTS
  fi

  # The safety net under the daily cleanup job: a lifecycle rule expires any
  # object left under the run prefix, whichever way its database row was lost.
  # Eight days is deliberately one day past the longest retention window, so the
  # application still owns deletion and this only catches what it missed.
  # Lifecycle rules are bucket settings rather than Worker configuration, which
  # is why they are provisioned here and not in wrangler.jsonc.
  if cf_wrangler r2 bucket lifecycle list "$BUCKET_NAME" 2>/dev/null | grep -q "expire-run-artifacts"; then
    note "Keeping the existing R2 lifecycle rule expire-run-artifacts."
  else
    cf_wrangler r2 bucket lifecycle add "$BUCKET_NAME" expire-run-artifacts "runs/" --expire-days 8 --force
  fi
fi
configure_wrangler "$INFRA_SLUG" "$D1_DATABASE_ID"
write_to_file "$SETUP_STATE_FILE" D1_DATABASE_ID "$D1_DATABASE_ID"
pnpm exec wrangler types

stage "Apply migrations and seed the database" 3
say "Migrations are additive. The foundation seed is an idempotent metadata marker."
say "The catalogue seed adds the synthetic distributor data every demo run needs."
say "Both seeds only insert missing rows, so re-running this never overwrites demo state."
if confirm "Apply pending D1 migrations to $DB_NAME now?"; then
  [[ "$WIZARD_DRY_RUN" == "1" ]] || cf_wrangler d1 migrations apply DB --remote
else
  die "Remote migrations were not approved."
fi
if confirm "Import the idempotent foundation and catalogue seeds now?"; then
  if [[ "$WIZARD_DRY_RUN" != "1" ]]; then
    cf_wrangler d1 execute DB --remote --file ./seed/foundation.sql
    cf_wrangler d1 execute DB --remote --file ./seed/catalog.sql
  fi
else
  die "Seed import was not approved."
fi

stage "Build and deploy the Worker" 4
APP_URL=$(saved_value "$SETUP_STATE_FILE" APP_URL || true)
[[ -n "$APP_URL" ]] && note "Previous application URL: $APP_URL"
confirm "Build and deploy the Worker, assets, and Workflow now?" || die "Deployment was not approved."
if [[ "$WIZARD_DRY_RUN" == "1" ]]; then
  APP_URL="https://${INFRA_SLUG}.example.workers.dev"
  note "dry run: would deploy $INFRA_SLUG"
else
  pnpm build:client
  DEPLOY_LOG=$(mktemp)
  cf_wrangler deploy | tee "$DEPLOY_LOG"
  APP_URL=$(grep -Eo 'https://[^[:space:]]+\.workers\.dev' "$DEPLOY_LOG" | tail -n1 || true)
  rm -f "$DEPLOY_LOG"
  if [[ -z "$APP_URL" ]]; then
    ask APP_URL "Paste the workers.dev URL printed by Wrangler:"
  fi
fi
write_to_file "$SETUP_STATE_FILE" APP_URL "$APP_URL"

stage "Mistral OCR access" 3
open_setup_url "https://console.mistral.ai/api-keys/"
step "Sign in, open API keys, create a key for this demo, and copy it once."
capture_secret "$DEV_VARS_FILE" MISTRAL_API_KEY "Paste the Mistral API key:"
MISTRAL_API_KEY=$(saved_value "$DEV_VARS_FILE" MISTRAL_API_KEY)

stage "Spend-limited OpenRouter access" 4
open_setup_url "https://openrouter.ai/settings/credits"
step "Add only the small credit amount you want available to this public demo."
step "Enable a usage limit or auto-refill ceiling that matches that budget."
pause "Press Enter after the spend limit is in place."
open_setup_url "https://openrouter.ai/workspaces/default/keys"
step "Create a key dedicated to this demo and copy it."
capture_secret "$DEV_VARS_FILE" OPENROUTER_API_KEY "Paste the OpenRouter API key:"
OPENROUTER_API_KEY=$(saved_value "$DEV_VARS_FILE" OPENROUTER_API_KEY)

stage "Cookieless EU PostHog project" 4
open_setup_url "https://eu.posthog.com/signup"
step "Create or select an EU Cloud project for this demo."
step "In Project settings, copy the Project API key. Keep session replay and person profiles disabled."
step "The application will use cookieless pageview capture against https://eu.i.posthog.com."
capture_secret "$DEV_VARS_FILE" POSTHOG_API_KEY "Paste the PostHog project API key:"
POSTHOG_API_KEY=$(saved_value "$DEV_VARS_FILE" POSTHOG_API_KEY)

stage "Local and encrypted Worker secrets" 3
RATE_LIMIT_SALT=$(saved_value "$DEV_VARS_FILE" RATE_LIMIT_SALT || true)
if [[ -z "$RATE_LIMIT_SALT" ]]; then
  RATE_LIMIT_SALT=$(node -e 'process.stdout.write(require("node:crypto").randomBytes(32).toString("hex"))')
  write_to_file "$DEV_VARS_FILE" RATE_LIMIT_SALT "$RATE_LIMIT_SALT"
else
  note "Keeping the existing rate-limit salt."
fi
say "Provider keys stay in ignored local state and encrypted Worker secrets; they never go to GitHub."
confirm "Upload the four Worker secrets now?" || die "Worker secret upload was not approved."
put_worker_secret MISTRAL_API_KEY "$MISTRAL_API_KEY"
put_worker_secret OPENROUTER_API_KEY "$OPENROUTER_API_KEY"
put_worker_secret POSTHOG_API_KEY "$POSTHOG_API_KEY"
put_worker_secret RATE_LIMIT_SALT "$RATE_LIMIT_SALT"

stage "GitHub Actions deployment settings" 2
say "CI receives only the Cloudflare deployment token and account ID."
confirm "Set CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID on the GitHub repository?" || die "GitHub Actions configuration was not approved."
if [[ "$WIZARD_DRY_RUN" == "1" ]]; then
  note "dry run: would set one GitHub secret and one repository variable"
else
  set_secret CLOUDFLARE_API_TOKEN "$CF_DEPLOY_TOKEN"
  set_var CLOUDFLARE_ACCOUNT_ID "$CF_ACCOUNT_ID"
fi

stage "Public health check" 2
say "Checking $APP_URL/api/health"
if [[ "$WIZARD_DRY_RUN" == "1" ]]; then
  note "dry run: would health-check and open $APP_URL"
elif command -v curl >/dev/null 2>&1 && HEALTH_BODY=$(curl --fail --silent "$APP_URL/api/health"); then
  printf '  %s✓ healthy%s %s\n' "$GREEN" "$RESET" "$HEALTH_BODY"
else
  warn "The health check did not pass. Inspect the deployment before publishing."
  die "Public verification failed."
fi
open_setup_url "$APP_URL"
pause "Confirm the anonymous application opens, then press Enter."

stage "Review, commit, and push" 4
say "Local secrets, setup state, generated runtime state, and .scratch are ignored."
git status --short
confirm "Stage the current repository files for publication?" || die "Staging was not approved."
if [[ "$WIZARD_DRY_RUN" == "1" ]]; then
  note "dry run: would stage repository files"
else
  git add --all
  git diff --cached --check
  printf '\n'
  git diff --cached --name-status
  printf '\n'

  if git diff --cached --quiet; then
    note "No new changes need a commit."
  else
    confirm "Commit exactly the staged files shown above?" || die "Commit was not approved."
    git commit -m "Establish RFQ Relay foundation"
  fi

  confirm "Push the current commit to origin/main?" || die "Push was not approved."
  git push --set-upstream origin HEAD:main
fi

ENV_FILE="$SETUP_STATE_FILE and $DEV_VARS_FILE"
finish
